### ISSUE TITLE
Update the tutorial code to be compatible with windows crate version 0.35.0

### ISSUE THREAD

**Issue by varunkamra** [MicrosoftDocs/windows-uwp#3780]
Please update the documentation so that the code written in the tutorial is compatible with latest windows crate version 0.35.0. Currently using windows::build! macro gives an error saying build! macro not found. Even when I used windows::core::build! it still failed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a621c9b-3a97-3d49-4de9-b309a491a75b
* Version Independent ID: 492ab689-9940-02ee-2f38-bafcd1dc9ad2
* Content: [RSS reader tutorial (Rust for Windows with VS Code)](https://docs.microsoft.com/en-us/windows/dev-environment/rust/rss-reader-rust-for-windows)
* Content Source: [hub/dev-environment/rust/rss-reader-rust-for-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/rss-reader-rust-for-windows.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for the heads up, @varunkamra. I've created a work item for myself (on my backlog) to take a look at this. That work item contains a link to this GitHub issue, so I'll go ahead and close this issue for now (so that I'm not tracking the work in two places), and I'll reopen this issue when I get to my work item.

Thanks again!
Steve

**Comment by varunkamra** [comment]
Sounds good, thank you! Although, would you mind telling me how to fix this issue? I haven’t been able to figure this out myself. Does build macro not exist anymore? I tried using window::build!() and windows::core::build!() but that did not work with 0.35.0 version so I had to use the 0.9.0 as mentioned in the doc to get it working.

**Comment by jaypatrick** [comment]
It's been 2 months, looks like the sample code has not been updated as we are now on v .37, throws error mentioned in this thread:


error[E0433]: failed to resolve: could not find `build` in `windows`
 --> bindings\build.rs:3:14
  |
3 |     windows::build!(
  |              ^^^^^ could not find `build` in `windows`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `bindings` due to previous error

**Comment by mbartlett21** [comment]
For whoever's following along on this issue:

`windows-rs` now no longer requires you to have a separate bindings crate, instead just using it directly, and enabling the features you need. To find out what features are needed for a function or type, you can find it in the crate docs ([link](https://microsoft.github.io/windows-docs-rs/doc/windows/)), and it tells you what features need to be enabled to have access to that function.

```toml
# in Cargo.toml
[dependencies.windows]
version = "0.37"
features = [
    "alloc", # conversion to HSTRING
    "Foundation",
    "Foundation_Collections",
    "Web_Syndication",
    "Win32_Foundation",
]
```

```rs
use windows::{ 
    Foundation::Uri,
    Web::Syndication::SyndicationClient,
};


async fn main_() -> windows::core::Result<()> {
    let uri = Uri::CreateUri("https://blogs.windows.com/feed")?;
    let client = SyndicationClient::new()?;
    // .get() blocks on an async operation
    let feed = client.RetrieveFeedAsync(uri)?.get()?;

    for item in feed.Items()? {
        println!("{}", item.Title()?.Text()?);
    }

    Ok(())
}
```

**Comment by modulozero** [comment]
What @mbartlett21 said, but also note that the tutorial's result is present in [the samples for the windows crate](https://github.com/microsoft/windows-rs/tree/master/crates/samples/rss) - latest version, 0.39, has a tiny difference (there are new string macros in the crate). 

I'd love to see the tutorial itself updated - it was the first thing I found when looking for a way to make a windows application with Rust, and the narrative structure can be helpful. I _also_ understand this is a dynamic package that will probably change faster than the tutorial can be updated.

Therefore, maybe I suggest editing the tutorial to make it clear that it's for a _specific version_ of the windows crate, and _why_? I personally would love it updated to .39, because the removal of the bindings sub-project makes the thing far cleaner, and constitutes a considerable difference from "past practice" - but even as is, it's a useful tutorial, as long as people don't get punished for doing the "reasonable by default" thing of updating the minor version.

Mind you, the minor version "guarantees" don't really apply for 0.something version, but I don't think it's weird that people often forget that.
